name: math_solver
description: Une application pour résoudre des problèmes mathématiques

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  http: ^1.1.0
  http_parser: ^4.0.2
  mime_type: ^1.0.0
  file_picker: ^10.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/



flutter_launcher_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true